//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Bot.Sample.SimpleFacebookAuthBot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int Id { get; set; }
        public string UserID { get; set; }
        public string AccountType { get; set; }
        public string ToFrom { get; set; }
        public decimal Value { get; set; }
        public decimal NewBalance { get; set; }
        public System.DateTime Created { get; set; }
        public string Message { get; set; }
    }
}
